# http://docs.ansible.com/ansible/latest/galaxy.html#installing-multiple-roles-from-a-file
---
- src: geerlingguy.firewall
- src: geerlingguy.git                # https://github.com/geerlingguy/ansible-role-git
- src: apolloclark.nano-highlighting  # https://github.com/apolloclark/ansible-role-nano-highlighting
- src: apolloclark.aws-cli            # https://github.com/apolloclark/ansible-role-aws-cli
- src: apolloclark.osquery            # https://github.com/apolloclark/ansible-role-osquery
- src: apolloclark.filebeat           # https://github.com/apolloclark/ansible-role-filebeat
- src: apolloclark.metricbeat         # https://github.com/apolloclark/ansible-role-metricbeat
- src: apolloclark.heartbeat          # https://github.com/apolloclark/ansible-role-heartbeat
- src: apolloclark.packetbeat         # https://github.com/apolloclark/ansible-role-packetbeat
